# Generated by Django 4.2.15 on 2024-08-28 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='first_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='users',
            name='last_name',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
