# Generated by Django 4.2.15 on 2024-08-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_first_name_alter_users_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cell',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
