# Generated by Django 4.2.15 on 2024-08-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('street_name', models.CharField(max_length=100)),
                ('street_number', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postcode', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timezone_offset', models.CharField(max_length=10)),
                ('timezone_description', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('dob', models.DateTimeField()),
                ('registered', models.DateTimeField()),
                ('phone', models.CharField(max_length=20)),
                ('cell', models.CharField(max_length=20)),
                ('nat', models.CharField(max_length=5)),
                ('picture_large', models.URLField()),
                ('picture_medium', models.URLField()),
                ('picture_thumbnail', models.URLField()),
            ],
        ),
    ]
